instruments: Add Perfetto instrument
ARM-software/workload-automation pull request #1203
Opened 2023-02-07 14:14 UTC by mrkajetanp

This PR intends to add a Perfetto instrument that allows workload-automation to attach collecting a Perfetto trace to a running workload. The first two commits amend the framework to make it possible to perform the validation necessary to make sure Perfetto isn't enabled at the same time as trace-cmd as trying to enable both simultaneously will result in both of them producing incorrect output. This is because both frameworks use the Linux Kernel's ftrace under the hood and will both try to configure it for themselves while interfering with each other's expected operation.

2023-05-16 22:28 UTC, marcbonnici requested changes

2023-05-23 16:17 UTC, mrkajetanp commented on wa/instruments/perfetto.py
> +    def validate(self, context):
all right, fixed

2023-09-06 21:57 UTC, marcbonnici reviewed
LGTM, last few nits just to keep the linter [1] happy.
[1] https://github.com/ARM-software/workload-automation/actions/runs/6038173655/job/16561897216?pr=1203

2023-09-06 21:57 UTC, marcbonnici commented on wa/instruments/perfetto.py
> +
nit: trailing new line

2023-09-06 21:57 UTC, marcbonnici commented on wa/instruments/perfetto.py
> +from wa.framework import signal
nit: Unused import

2023-09-06 21:57 UTC, marcbonnici commented on wa/instruments/perfetto.py
> +    def start(self, context):
`# pylint: disable=unused-argument`

2023-09-06 21:57 UTC, marcbonnici commented on wa/instruments/perfetto.py
> +    def stop(self, context):
`# pylint: disable=unused-argument`

2023-09-06 21:57 UTC, marcbonnici commented on wa/instruments/perfetto.py
> +    def teardown(self, context):
`# pylint: disable=unused-argument`

2023-09-06 21:57 UTC, marcbonnici commented on wa/instruments/perfetto.py
> +    def finalize(self, context):
`# pylint: disable=unused-argument`

2023-09-06 21:57 UTC, marcbonnici commented on wa/instruments/perfetto.py
> +    def initialize(self, context):
`# pylint: disable=unused-argument`

2023-09-07 14:22 UTC, mrkajetanp commented
Updated, the liner is now happy :)

2023-09-07 22:29 UTC, marcbonnici approved these changes

2023-09-07 22:29 UTC, merged